version: "3"
volumes:
    nominatim-data:
services:
    web:
        image: nginx:alpine
        restart: always
        stop_grace_period: 0s
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        stop_grace_period: 0s
        environment:
            PORT: 3333
        volumes:
            - ./data:/data
            - ../:/app
        networks:
            - network

    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.3
        stop_grace_period: 0s
        ports:
            - "4444:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.3#configuration for more options
            PBF_URL: https://download.geofabrik.de/europe/austria-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/europe/austria-updates/
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb
        networks:
            - network

networks:
    network:
        driver: bridge
